[package]
name = "minify-html-ssr"
version = "0.1.0"
authors = ["scott-newcomer <snewcomer24@gmail.com>"]
edition = "2018"

[lib]
name = "minify_html_ssr"
src = "src/lib.rs"
# crate-type = ["cdylib"]

[[bin]]
name = "minify_html_ssr"
src = "src/bin"

[dependencies]
wasm-bindgen = "0.2.73"
